site_name: JTE for All

theme:
  name: material
  highlightjs: true
  hljs_styles: Felipec
  hljs_languages:
    - groovy
    - java
  palette:
    primary: teal
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

repo_url: https://https://github.com/DeadlyChambers/k8s-jte

watch:
- libraries

plugins:
  - search:
  - gen-files:
      scripts:
        - /docs/resources/copy_docs.py

# extra:
#   version:
#     provider: mike
#     default: latest

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight